name: CI-CD

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  validate:
    name: Validation sécurité et qualité
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        working-directory: ./api
        run: npm install

      - name: Lint
        working-directory: ./api
        run: npm run lint

      - name: Format check
        working-directory: ./api
        run: npm run format

      - name: SAST (npm audit)
        working-directory: ./api
        run: npm audit --audit-level=moderate

      - name: Gitleaks Secret Scan
        uses: gitleaks/gitleaks-action@v2
        env:
            GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}


  test:
    name: Tests API
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        working-directory: ./api
        run: npm install
      - name: Run tests
        working-directory: ./api
        run: npm test
